[Bash] Fix live replay script.

diff --git a/scripts/aeron/remote-live-replay-benchmarks b/scripts/aeron/remote-live-replay-benchmarks
--- a/scripts/aeron/remote-live-replay-benchmarks
+++ b/scripts/aeron/remote-live-replay-benchmarks
@@ -31,7 +31,6 @@ required_vars=(
   "CLIENT_LOAD_TEST_RIG_MAIN_CPU_CORE"
   "CLIENT_LOAD_TEST_RIG_OTHER_CPU_CORES"
   "CLIENT_INTERFACE"
-  "CLIENT_INTERFACE"
   "SERVER_JAVA_HOME"
   "SERVER_DRIVER_CONDUCTOR_CPU_CORE"
   "SERVER_DRIVER_SENDER_CPU_CORE"
@@ -41,7 +40,6 @@ required_vars=(
   "SERVER_ARCHIVE_REPLAYER_CPU_CORE"
   "SERVER_ARCHIVE_CONDUCTOR_CPU_CORE"
   "SERVER_ARCHIVE_OTHER_CPU_CORES"
-  "SERVER_INTERFACE"
   "SERVER_INTERFACE"
   "DESTINATION_IP"
   "SOURCE_IP"
@@ -67,6 +65,7 @@ so_rcvbuf="${AERON_SOCKET_SO_RCVBUF:-2m}"
 rcv_initial_window="${AERON_RCV_INITIAL_WINDOW_LENGTH:-2m}"
 
 enable_c_driver=1
+no_c_driver=0
 enable_java_driver=1
 enable_ef_vi=1
 enable_dpdk=1
@@ -78,17 +77,21 @@ onload="onload --profile=latency --force-profiles "
 while [[ $# -gt 0 ]]
 do
   case "${1}" in
-  --onload)
-    onload="${2}"
-    shift
-    shift
-    ;;
-  --no-c-driver)
+  --disable-c-driver)
     enable_c_driver=0
     shift
     ;;
-  --no-java-driver)
+  --no-c-driver)
+    no_c_driver=1
+    shift
+    ;;
+  --disable-java-driver)
     enable_java_driver=0
+    shift
+    ;;
+  --onload)
+    onload="${2}"
+    shift
     shift
     ;;
   --no-ef_vi)
@@ -119,13 +122,13 @@ do
     shift
     ;;
   -h|--help)
-    echo "${0} [--onload \"\$onload_command\"] [--no-ef_vi] [--no-dpdk] [--no-c-driver] [--no-java-driver] [--file-sync-level \"\${file-sync-level-csv}\"] [--mtu \"\$mtu-csv\"]"
+    echo "${0} [--onload \"\$onload_command\"] [--no-ef_vi] [--no-dpdk] [--disable-c-driver] [--no-c-driver] [--disable-java-driver] [--file-sync-level \"\${file-sync-level-csv}\"] [--mtu \"\$mtu-csv\"]"
     exit
     ;;
-    *)
-      echo "Invalid parameter. Use --help to get a list of supported parameters."
-      exit 1
-      ;;
+  *)
+    echo "Invalid parameter: ${1}. Use --help to get a list of supported parameters."
+    exit 1
+    ;;
   esac
 done
 
@@ -162,15 +165,18 @@ fi
 
 if [ "${enable_c_driver}" -eq 1 ]
 then
-  if [ -n "${onload}" ]
+  if [ "${no_c_driver}" -eq 0 ]
   then
-    scenarios+=("c-onload")
-  else
-    scenarios+=("c")
+    if [ -n "${onload}" ]
+    then
+      scenarios+=("c-onload")
+    else
+      scenarios+=("c")
+    fi
+    commands+=("${driver_properties}; \
+      export EF_NO_FAIL=0 EF_RXQ_SIZE=${ef_vi_rxq_size} EF_TXQ_SIZE=${ef_vi_txq_size} \
+      && $(start_media_driver "${scripts_path}/c-media-driver" "${onload}" "driver_other_cpu_cores_var" "driver_conductor_cpu_core_var" "driver_sender_cpu_core_var" "driver_receiver_cpu_core_var")")
   fi
-  commands+=("${driver_properties}; \
-    export EF_NO_FAIL=0 EF_RXQ_SIZE=${ef_vi_rxq_size} EF_TXQ_SIZE=${ef_vi_txq_size} \
-    && $(start_media_driver "${scripts_path}/c-media-driver" "${onload}" "driver_other_cpu_cores_var" "driver_conductor_cpu_core_var" "driver_sender_cpu_core_var" "driver_receiver_cpu_core_var")")
 
   if [ "${enable_ef_vi}" -eq 1 ]
   then
@@ -245,6 +251,8 @@ do
       -Duk.co.real_logic.benchmarks.aeron.remote.destination.channel=aeron:udp?endpoint=${DESTINATION_IP}:13000|interface=${SERVER_INTERFACE} \
       -Duk.co.real_logic.benchmarks.aeron.remote.source.channel=aeron:udp?endpoint=${SOURCE_IP}:13100|interface=${SERVER_INTERFACE} \
       -Daeron.archive.control.channel=aeron:udp?endpoint=${DESTINATION_IP}:13200|interface=${SERVER_INTERFACE} \
+      -Daeron.archive.control.response.channel=aeron:udp?endpoint=${DESTINATION_IP}:0|interface=${SERVER_INTERFACE} \
+      -Daeron.archive.replication.channel=aeron:udp?endpoint=${DESTINATION_IP}:0|interface=${SERVER_INTERFACE} \
       -Daeron.archive.dir=${ARCHIVE_DIR} \
       -Daeron.archive.file.sync.level=${fsync} \
       -Daeron.archive.catalog.file.sync.level=${fsync} \
@@ -265,7 +273,7 @@ do
         "uk.co.real_logic.benchmarks.remote.output.file=${test}" \
         "uk.co.real_logic.benchmarks.remote.output.directory=${CLIENT_BENCHMARKS_PATH}/scripts/results" \
         "uk.co.real_logic.benchmarks.aeron.remote.destination.channel=aeron:udp?endpoint=${DESTINATION_IP}:13000|interface=${CLIENT_INTERFACE}" \
-        "uk.co.real_logic.benchmarks.aeron.remote.source.channel=aeron:udp?endpoint=${AERON_SOURCE_IP}:13100|interface=${CLIENT_INTERFACE}" \
+        "uk.co.real_logic.benchmarks.aeron.remote.source.channel=aeron:udp?endpoint=${SOURCE_IP}:13100|interface=${CLIENT_INTERFACE}" \
         "aeron.archive.control.channel=aeron:udp?endpoint=${DESTINATION_IP}:13200|interface=${CLIENT_INTERFACE}" \
         "aeron.archive.control.response.channel=aeron:udp?endpoint=${SOURCE_IP}:0|interface=${CLIENT_INTERFACE}" \
         "aeron.archive.message.timeout=30000000000"
