[Gradle] Add task for creating a tar for deployment [Bash] Tidy up and add robustness checks [Python] Add fabric script for deployment

diff --git a/scripts/aeron/remote-cluster-benchmarks b/scripts/aeron/remote-cluster-benchmarks
--- a/scripts/aeron/remote-cluster-benchmarks
+++ b/scripts/aeron/remote-cluster-benchmarks
@@ -15,6 +15,8 @@
 ## limitations under the License.
 ##
 
+set -euo pipefail
+
 DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" >/dev/null 2>&1 && pwd)"
 
 if [ -z "${MESSAGE_RATE}" ];
@@ -70,7 +72,7 @@ for var in "${required_vars[@]}"; do
   fi
 done
 
-if [ -n "${required_var_missing}" ]
+if [[ -v required_var_missing && -n "${required_var_missing}" ]]
 then
   exit 1
 fi
@@ -133,7 +135,7 @@ do
     exit
     ;;
   *)
-    echo "Invalid parameter. Use --help to get a list of supported parameters."
+    echo "Invalid parameter '${1}'. Use --help to get a list of supported parameters."
     exit 1
     ;;
   esac
