[Bash] Add command line options to override what is tested, e.g. `--no-ats` disables the ATS tests.

diff --git a/scripts/aeron/remote-echo-benchmarks b/scripts/aeron/remote-echo-benchmarks
--- a/scripts/aeron/remote-echo-benchmarks
+++ b/scripts/aeron/remote-echo-benchmarks
@@ -51,6 +51,49 @@ then
   exit 1
 fi
 
+enable_onload=1
+enable_ef_vi=1
+enable_ats=1
+enable_c_driver=1
+active_publications=(1 2 5 10)
+
+while [[ $# -gt 0 ]]
+do
+  case "$1" in
+    --no-onload)
+      enable_onload=0
+      shift
+      ;;
+    --no-ef_vi)
+      enable_ef_vi=0
+      shift
+      ;;
+    --no-ats)
+      enable_ats=0
+      shift
+      ;;
+    --no-c-driver)
+      enable_c_driver=0
+      shift
+      ;;
+    --active-publications)
+      IFS=',';
+      read -ra active_publications <<< "$2"
+      unset IFS;
+      shift
+      shift
+      ;;
+    -h|--help)
+      echo "$0 [--no-onload] [--no-ef_vi] [--no-ats] [--no-c-driver] [--active-publications \"\$active-publications-csv\"]"
+      exit
+      ;;
+    *)
+      echo "Invalid parameter. Use --help to get a list of supported parameters."
+      exit 1
+      ;;
+  esac
+done
+
 function build_drivers()
 {
   local commands=()
@@ -58,73 +101,130 @@ function build_drivers()
   # Java driver
   commands+=("$(start_media_driver "$BENCHMARKS_PATH/scripts/aeron/media-driver" "$1" "$2" "$3" "$4")")
 
-  # Java driver with Onload
-  commands+=("$(start_media_driver \
-    "onload --profile=latency --force-profiles $BENCHMARKS_PATH/scripts/aeron/media-driver" "$1" "$2" "$3" "$4")")
+  if [ "$enable_onload" -eq 1 ]
+  then
+    # Java driver with Onload
+    commands+=("$(start_media_driver \
+      "onload --profile=latency --force-profiles $BENCHMARKS_PATH/scripts/aeron/media-driver" "$1" "$2" "$3" "$4")")
+  fi
 
-  # C driver
-  commands+=("$(start_media_driver "$BENCHMARKS_PATH/scripts/aeron/c-media-driver" "$1" "$2" "$3" "$4")")
+  if [ "$enable_c_driver" -eq 1 ]
+  then
+    # C driver
+    commands+=("$(start_media_driver "$BENCHMARKS_PATH/scripts/aeron/c-media-driver" "$1" "$2" "$3" "$4")")
 
-  # C driver with Onload
-  commands+=("$(start_media_driver \
-    "onload --profile=latency --force-profiles $BENCHMARKS_PATH/scripts/aeron/c-media-driver" "$1" "$2" "$3" "$4")")
+    if [ "$enable_onload" -eq 1 ]
+    then
+      # C driver with Onload
+      commands+=("$(start_media_driver \
+        "onload --profile=latency --force-profiles $BENCHMARKS_PATH/scripts/aeron/c-media-driver" "$1" "$2" "$3" "$4")")
+    fi
 
-  # C driver with ef_vi
-  commands+=("$(start_media_driver \
-    "AERON_UDP_CHANNEL_TRANSPORT_BINDINGS_MEDIA=\"aeron_udp_channel_transport_ef_vi_bindings\" \
-    AERON_DRIVER_DYNAMIC_LIBRARIES=\"$BENCHMARKS_PATH/scripts/aeron/libaeron_ef_vi.so\" \
-    $BENCHMARKS_PATH/scripts/aeron/c-media-driver" "$1" "$2" "$3" "$4")")
+    if [ "$enable_ef_vi" -eq 1 ]
+    then
+      # C driver with ef_vi
+      commands+=("$(start_media_driver \
+        "AERON_UDP_CHANNEL_TRANSPORT_BINDINGS_MEDIA=\"aeron_udp_channel_transport_ef_vi_bindings\" \
+        AERON_DRIVER_DYNAMIC_LIBRARIES=\"$BENCHMARKS_PATH/scripts/aeron/libaeron_ef_vi.so\" \
+        $BENCHMARKS_PATH/scripts/aeron/c-media-driver" "$1" "$2" "$3" "$4")")
+    fi
 
-  # C driver with ATS
-  commands+=("$(start_media_driver \
-    "AERON_TRANSPORT_SECURITY_CONF_DIR=\"$BENCHMARKS_PATH/scripts/aeron\" \
-    AERON_TRANSPORT_SECURITY_CONF_FILE=ats.conf \
-    AERON_UDP_CHANNEL_OUTGOING_INTERCEPTORS=\"aeron_transport_security_channel_interceptor_load\" \
-    AERON_UDP_CHANNEL_INCOMING_INTERCEPTORS=\"aeron_transport_security_channel_interceptor_load\" \
-    AERON_DRIVER_DYNAMIC_LIBRARIES=\"$BENCHMARKS_PATH/scripts/aeron/libaeron_transport_security.so\" \
-    $BENCHMARKS_PATH/scripts/aeron/c-media-driver" "$1" "$2" "$3" "$4")")
+    if [ "$enable_ats" -eq 1 ]
+    then
+      # C driver with ATS
+      commands+=("$(start_media_driver \
+        "AERON_TRANSPORT_SECURITY_CONF_DIR=\"$BENCHMARKS_PATH/scripts/aeron\" \
+        AERON_TRANSPORT_SECURITY_CONF_FILE=ats.conf \
+        AERON_UDP_CHANNEL_OUTGOING_INTERCEPTORS=\"aeron_transport_security_channel_interceptor_load\" \
+        AERON_UDP_CHANNEL_INCOMING_INTERCEPTORS=\"aeron_transport_security_channel_interceptor_load\" \
+        AERON_DRIVER_DYNAMIC_LIBRARIES=\"$BENCHMARKS_PATH/scripts/aeron/libaeron_transport_security.so\" \
+        $BENCHMARKS_PATH/scripts/aeron/c-media-driver" "$1" "$2" "$3" "$4")")
 
-  # C driver with ATS and Onload
-  commands+=("$(start_media_driver \
-    "AERON_TRANSPORT_SECURITY_CONF_DIR=\"$BENCHMARKS_PATH/scripts/aeron\" \
-    AERON_TRANSPORT_SECURITY_CONF_FILE=ats.conf \
-    AERON_UDP_CHANNEL_OUTGOING_INTERCEPTORS=\"aeron_transport_security_channel_interceptor_load\" \
-    AERON_UDP_CHANNEL_INCOMING_INTERCEPTORS=\"aeron_transport_security_channel_interceptor_load\" \
-    AERON_DRIVER_DYNAMIC_LIBRARIES=\"$BENCHMARKS_PATH/scripts/aeron/libaeron_transport_security.so\" \
-    onload --profile=latency --force-profiles $BENCHMARKS_PATH/scripts/aeron/c-media-driver" "$1" "$2" "$3" "$4")")
+      if [ "$enable_onload" -eq 1 ]
+      then
+        # C driver with ATS and Onload
+        commands+=("$(start_media_driver \
+          "AERON_TRANSPORT_SECURITY_CONF_DIR=\"$BENCHMARKS_PATH/scripts/aeron\" \
+          AERON_TRANSPORT_SECURITY_CONF_FILE=ats.conf \
+          AERON_UDP_CHANNEL_OUTGOING_INTERCEPTORS=\"aeron_transport_security_channel_interceptor_load\" \
+          AERON_UDP_CHANNEL_INCOMING_INTERCEPTORS=\"aeron_transport_security_channel_interceptor_load\" \
+          AERON_DRIVER_DYNAMIC_LIBRARIES=\"$BENCHMARKS_PATH/scripts/aeron/libaeron_transport_security.so\" \
+          onload --profile=latency --force-profiles $BENCHMARKS_PATH/scripts/aeron/c-media-driver" "$1" "$2" "$3" "$4")")
+      fi
 
-  # C driver with ATS and ef_vi
-  commands+=("$(start_media_driver \
-    "AERON_TRANSPORT_SECURITY_CONF_DIR=\"$BENCHMARKS_PATH/scripts/aeron\" \
-    AERON_TRANSPORT_SECURITY_CONF_FILE=ats.conf \
-    AERON_UDP_CHANNEL_OUTGOING_INTERCEPTORS=\"aeron_transport_security_channel_interceptor_load\" \
-    AERON_UDP_CHANNEL_INCOMING_INTERCEPTORS=\"aeron_transport_security_channel_interceptor_load\" \
-    AERON_DRIVER_DYNAMIC_LIBRARIES=\"$BENCHMARKS_PATH/scripts/aeron/libaeron_transport_security.so\",\"$BENCHMARKS_PATH/scripts/aeron/libaeron_ef_vi.so\" \
-    AERON_UDP_CHANNEL_TRANSPORT_BINDINGS_MEDIA=\"aeron_udp_channel_transport_ef_vi_bindings\" \
-    $BENCHMARKS_PATH/scripts/aeron/c-media-driver" "$1" "$2" "$3" "$4")")
+      if [ "$enable_ef_vi" -eq 1 ]
+      then
+        # C driver with ATS and ef_vi
+        commands+=("$(start_media_driver \
+          "AERON_TRANSPORT_SECURITY_CONF_DIR=\"$BENCHMARKS_PATH/scripts/aeron\" \
+          AERON_TRANSPORT_SECURITY_CONF_FILE=ats.conf \
+          AERON_UDP_CHANNEL_OUTGOING_INTERCEPTORS=\"aeron_transport_security_channel_interceptor_load\" \
+          AERON_UDP_CHANNEL_INCOMING_INTERCEPTORS=\"aeron_transport_security_channel_interceptor_load\" \
+          AERON_DRIVER_DYNAMIC_LIBRARIES=\"$BENCHMARKS_PATH/scripts/aeron/libaeron_transport_security.so\",\"$BENCHMARKS_PATH/scripts/aeron/libaeron_ef_vi.so\" \
+          AERON_UDP_CHANNEL_TRANSPORT_BINDINGS_MEDIA=\"aeron_udp_channel_transport_ef_vi_bindings\" \
+          $BENCHMARKS_PATH/scripts/aeron/c-media-driver" "$1" "$2" "$3" "$4")")
+      fi
+    fi
+  fi
 
   local IFS=$'\n'
   echo "${commands[*]}"
 }
 
-OLD_IFS=$IFS
 IFS=$'\n'
 client_drivers=($(build_drivers "$CLIENT_DRIVER_OTHER_CPU_CORES" "$CLIENT_DRIVER_CPU_CORE_1" "$CLIENT_DRIVER_CPU_CORE_2" "$CLIENT_DRIVER_CPU_CORE_3"))
 server_drivers=($(build_drivers "$SERVER_DRIVER_OTHER_CPU_CORES" "$SERVER_DRIVER_CPU_CORE_1" "$SERVER_DRIVER_CPU_CORE_2" "$SERVER_DRIVER_CPU_CORE_3"))
-IFS=$OLD_IFS
+unset IFS
 
-scenarios=("java" "java-onload" "c" "c-onload" "c-ef_vi" "c-ats" "c-ats-onload" "c-ats-ef_vi")
+scenarios=("java")
+
+if [ "$enable_onload" -eq 1 ]
+then
+  scenarios+=("java-onload")
+fi
+
+if [ "$enable_c_driver" -eq 1 ]
+then
+  scenarios+=("c")
+
+  if [ "$enable_onload" -eq 1 ]
+  then
+    scenarios+=("c-onload")
+  fi
+
+  if [ "$enable_ef_vi" -eq 1 ]
+  then
+    scenarios+=("c-ef_vi")
+  fi
+
+  if [ "$enable_ats" -eq 1 ]
+  then
+    scenarios+=("c-ats")
+
+    if [ "$enable_onload" -eq 1 ]
+    then
+      scenarios+=("c-ats-onload")
+    fi
+
+    if [ "$enable_ef_vi" -eq 1 ]
+    then
+      scenarios+=("c-ats-ef_vi")
+    fi
+  fi
+fi
+
 for index in "${!scenarios[@]}"
 do
   scenario="${scenarios[index]}"
   client_driver="${client_drivers[index]}"
   server_driver="${server_drivers[index]}"
 
-  for active in 1 2 5 10
+  for active in "${active_publications[@]}"
   do
     for passive in 0 $active
     do
-      echo -e "\n Testing scenario: '$scenario', active=$active, passive=$passive\n"
+      test="echo-$scenario-active-$active-passive-$passive"
+      echo -e "\n Testing scenario: '$test'\n"
 
       destination_channels=""
       destination_streams=""
@@ -160,7 +260,7 @@ do
         "export JAVA_HOME=\"$SERVER_JAVA_HOME\" && $server_driver && taskset -c $SERVER_CPU_CORES $BENCHMARKS_PATH/scripts/aeron/echo-server" \
         "kill -9 $(find_java_process_by_class_name "uk.co.real_logic.benchmarks.aeron.remote.EchoNode"); $(stop_media_driver)" \
         "$BENCHMARKS_PATH/scripts/aeron/benchmark.properties" \
-        "uk.co.real_logic.benchmarks.remote.outputFileNamePrefix=echo-$scenario-active-$active-passive-$passive" \
+        "uk.co.real_logic.benchmarks.remote.outputFileNamePrefix=$test" \
         "uk.co.real_logic.benchmarks.remote.outputDirectory=$BENCHMARKS_PATH/scripts/results" \
         "uk.co.real_logic.benchmarks.aeron.remote.destination.channels=${destination_channels%?}" \
         "uk.co.real_logic.benchmarks.aeron.remote.destination.streams=${destination_streams%?}" \
